import { z } from 'zod'

const envSchema = z.object({
  NEXT_PUBLIC_SITE_URL: z.string().url().default('http://localhost:3000'),
  DATABASE_URI: z.string().min(1).default('postgres://postgres:postgres@localhost:5432/9life_mag'),
  PAYLOAD_SECRET: z.string().min(1).default('replace-me'),
  R2_ACCOUNT_ID: z.string().optional(),
  R2_ACCESS_KEY_ID: z.string().optional(),
  R2_SECRET_ACCESS_KEY: z.string().optional(),
  R2_BUCKET: z.string().default('9life-mag-private'),
  R2_ENDPOINT: z.string().optional(),
  R2_PUBLIC_BASE_URL: z.string().url().optional(),
  PAYMENT_PROVIDER_VN: z.string().optional(),
  PAYMENT_PROVIDER_GLOBAL: z.string().optional(),
  RESEND_API_KEY: z.string().optional(),
  GOOGLE_CLIENT_ID: z.string().optional(),
  GOOGLE_CLIENT_SECRET: z.string().optional(),
  FACEBOOK_APP_ID: z.string().optional(),
  FACEBOOK_APP_SECRET: z.string().optional(),
  RESET_PASSWORD_FROM_EMAIL: z.string().optional(),
  RESET_PASSWORD_FROM_NAME: z.string().optional(),
  CMS_ADMIN_EMAIL: z.string().optional(),
  CMS_ADMIN_PASSWORD: z.string().optional(),
  CMS_ADMIN_OTP_CODE: z.string().optional(),
  CMS_ADMIN_ROLE: z.string().optional(),
  CMS_SESSION_SECRET: z.string().optional(),
  SITE_SESSION_SECRET: z.string().optional(),
  SITE_USER_STORAGE_DRIVER: z.enum(['file', 'payload']).default('file')
})

export const env = envSchema.parse({
  NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
  DATABASE_URI: process.env.DATABASE_URI,
  PAYLOAD_SECRET: process.env.PAYLOAD_SECRET,
  R2_ACCOUNT_ID: process.env.R2_ACCOUNT_ID,
  R2_ACCESS_KEY_ID: process.env.R2_ACCESS_KEY_ID,
  R2_SECRET_ACCESS_KEY: process.env.R2_SECRET_ACCESS_KEY,
  R2_BUCKET: process.env.R2_BUCKET,
  R2_ENDPOINT: process.env.R2_ENDPOINT,
  R2_PUBLIC_BASE_URL: process.env.R2_PUBLIC_BASE_URL,
  PAYMENT_PROVIDER_VN: process.env.PAYMENT_PROVIDER_VN,
  PAYMENT_PROVIDER_GLOBAL: process.env.PAYMENT_PROVIDER_GLOBAL,
  RESEND_API_KEY: process.env.RESEND_API_KEY,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  FACEBOOK_APP_ID: process.env.FACEBOOK_APP_ID,
  FACEBOOK_APP_SECRET: process.env.FACEBOOK_APP_SECRET,
  RESET_PASSWORD_FROM_EMAIL: process.env.RESET_PASSWORD_FROM_EMAIL,
  RESET_PASSWORD_FROM_NAME: process.env.RESET_PASSWORD_FROM_NAME,
  CMS_ADMIN_EMAIL: process.env.CMS_ADMIN_EMAIL,
  CMS_ADMIN_PASSWORD: process.env.CMS_ADMIN_PASSWORD,
  CMS_ADMIN_OTP_CODE: process.env.CMS_ADMIN_OTP_CODE,
  CMS_ADMIN_ROLE: process.env.CMS_ADMIN_ROLE,
  CMS_SESSION_SECRET: process.env.CMS_SESSION_SECRET,
  SITE_SESSION_SECRET: process.env.SITE_SESSION_SECRET,
  SITE_USER_STORAGE_DRIVER: process.env.SITE_USER_STORAGE_DRIVER
})
