import Link from 'next/link'
import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import { createShareMetadata } from '@/lib/seo'
import { ArticleShareButton } from '@/components/article-share-button'
import { ContentDiscovery } from '@/components/content-discovery'
import { getSupplementArticleDetail, newsCatalogSupplement } from '@/lib/news-catalog-supplement'

type Article = { category: string; date: string; title: string; summary: string; image: string; body: string[] }

const articleMap: Record<string, Article> = {
  'dem-nhac-edm-quoc-te-tai-tp-hcm': { category: 'Sự kiện', date: '10 Tháng 7, 2026', title: 'Đêm nhạc EDM quốc tế thu hút 10.000 khán giả tại TP.HCM', summary: 'Sự kiện âm nhạc điện tử lớn nhất mùa hè quy tụ các DJ hàng đầu và một sân khấu giàu năng lượng.', image: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=1400&h=860&fit=crop', body: ['Đêm diễn đánh dấu một bước tiến mới của những sự kiện âm nhạc điện tử quy mô lớn tại Việt Nam, với hệ thống visual đồng bộ cùng line-up quốc tế.', 'Bên cạnh trải nghiệm sân khấu, các hoạt động cộng đồng và khu vực sáng tạo giúp khán giả kết nối với nghệ sĩ theo một cách gần gũi hơn.', 'Khi kết nối CMS, nội dung, ảnh cover, metadata SEO và bài liên quan sẽ được phân phối tự động theo slug bài viết.'] },
  'countdown-2027-ha-noi-lineup-dau-tien': { category: 'Sự kiện', date: '08 Tháng 7, 2026', title: 'Countdown 2027 công bố lineup đầu tiên tại Hà Nội', summary: 'Chuỗi sự kiện đón năm mới hứa hẹn bùng nổ với sân khấu 360 độ và những tên tuổi được chờ đợi.', image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1400&h=860&fit=crop', body: ['Lineup đầu tiên mang đến nhiều màu sắc từ electronic, pop đến những màn kết hợp live đặc biệt.', 'Ban tổ chức đang hoàn thiện trải nghiệm di chuyển, khu vực khán giả và lịch trình công bố các nghệ sĩ tiếp theo.', 'Độc giả có thể theo dõi những cập nhật mới nhất ngay trong chuỗi bài viết liên quan bên dưới.'] },
  'top-dj-viet-nam-dang-len-2026': { category: 'Âm nhạc', date: '09 Tháng 7, 2026', title: 'Top DJ Việt Nam đang lên: Xu hướng âm nhạc 2026', summary: 'Những cái tên trẻ đang làm mới bản đồ nightlife bằng sound hiện đại và cộng đồng riêng.', image: 'https://images.unsplash.com/photo-1571266028243-d220c9c3b73f?w=1400&h=860&fit=crop', body: ['Thế hệ DJ mới đang xây dựng dấu ấn thông qua sản phẩm cá nhân, set diễn giàu câu chuyện và khả năng kết nối với audience số.', 'Từ club residency đến festival, tiêu chuẩn trình diễn ngày càng đòi hỏi sự chỉn chu về âm thanh, hình ảnh và nhận diện.', 'Danh sách dưới đây tiếp tục mở rộng góc nhìn về nghệ sĩ và xu hướng đang định hình scene.'] },
  'hybrid-club-media-package': { category: 'Nightlife', date: '06 Tháng 7, 2026', title: 'Mô hình hybrid club đang thay đổi cách venue bán vé và media package', summary: 'Venue kết hợp trải nghiệm trực tiếp, nội dung số và gói truyền thông để tăng giá trị cho mỗi đêm diễn.', image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1400&h=860&fit=crop', body: ['Hybrid club không chỉ là một định dạng bán vé mà là cách venue phát triển cộng đồng và nội dung dài hạn.', 'Sau mỗi đêm diễn, aftermovie, ảnh recap và playlist trở thành tài sản giúp kéo dài vòng đời trải nghiệm.', 'Cách tiếp cận này giúp nghệ sĩ, venue và nhãn hàng cùng có thêm điểm chạm với người xem.'] },
  'echo-violet-producer-va-community': { category: 'Phỏng vấn', date: '05 Tháng 7, 2026', title: 'Echo Violet: “Producer giờ phải hiểu cả thương hiệu lẫn community”', summary: 'Chia sẻ về chiến lược xây catalog, live set và cách nghệ sĩ độc lập mở rộng nguồn thu.', image: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=1400&h=860&fit=crop', body: ['Echo Violet cho rằng âm nhạc chỉ là điểm bắt đầu. Một producer hiện đại cần hiểu cộng đồng, cách kể câu chuyện và các nền tảng nơi khán giả gặp gỡ nhau.', 'Với live set, phần visual và không gian biểu diễn cần được xem như một trải nghiệm thống nhất thay vì những mảnh ghép riêng lẻ.', 'Đó cũng là lý do nghệ sĩ đầu tư nhiều hơn vào catalog, media kit và mối quan hệ bền vững với audience.'] },
  'waveform-preview-signed-download-music-commerce': { category: 'Công nghệ', date: '04 Tháng 7, 2026', title: 'Waveform preview và signed download đang trở thành chuẩn mới cho music commerce', summary: 'Nền tảng âm nhạc số tối ưu trải nghiệm nghe thử, bản quyền và kiểm soát file master.', image: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=1400&h=860&fit=crop', body: ['Preview waveform giúp người nghe nhận diện nhanh cấu trúc và năng lượng của bản nhạc trước khi quyết định mua hoặc tải xuống.', 'Signed download tạo thêm lớp kiểm soát quan trọng cho file chất lượng cao và quyền truy cập premium.', 'Khi kết hợp với dữ liệu hành vi, hệ thống có thể gợi ý nội dung phù hợp hơn mà vẫn tôn trọng quyền phát hành.'] },
}

const feedArticleDetails: Record<string, Article> = {
  'aftermovie-club-recap-tao-traffic-moi': { category: 'Backstage', date: '06 Tháng 7, 2026', title: 'Aftermovie và recap sau show đang trở thành nguồn traffic mới cho venue', summary: 'Một kế hoạch recap đúng nhịp giúp venue kéo dài trải nghiệm đêm diễn và tạo lý do để khán giả quay lại.', image: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=1400&h=860&fit=crop', body: ['Aftermovie không còn chỉ là một video tổng kết. Nó là điểm chạm đầu tiên để người chưa tham dự cảm nhận năng lượng của venue.', 'Một gói recap hiệu quả cần có ảnh dọc, video ngắn, thông tin line-up và lời kêu gọi theo dõi đêm tiếp theo.', 'Khi được phân phối đúng thời điểm, nội dung hậu trường có thể biến một đêm diễn thành chuỗi tương tác kéo dài nhiều ngày.'] },
  'female-dj-premium-lounge-demand': { category: 'Artist', date: '05 Tháng 7, 2026', title: 'Nhu cầu female DJ cho premium lounge tăng mạnh trong mùa hè', summary: 'Venue tìm kiếm nghệ sĩ có cá tính âm nhạc, hình ảnh chỉn chu và khả năng đọc nhịp không gian.', image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=1400&h=860&fit=crop', body: ['Premium lounge cần một nhịp âm nhạc tinh tế nhưng vẫn đủ năng lượng để giữ khách ở lại lâu hơn.', 'Female DJ có profile rõ ràng thường tạo lợi thế khi venue cần kết hợp âm nhạc, hình ảnh và nội dung social.', 'Một media kit súc tích giúp đội booking chọn đúng nghệ sĩ theo khung giờ, tệp khách và concept đêm diễn.'] },
  'future-rave-prime-time-2026': { category: 'Âm nhạc', date: '04 Tháng 7, 2026', title: 'Future rave vẫn là lựa chọn prime-time hàng đầu của crowd 2026', summary: 'Cấu trúc drop rõ và năng lượng visual mạnh khiến future rave tiếp tục phù hợp cho khung giờ cao điểm.', image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1400&h=860&fit=crop', body: ['Future rave phát huy hiệu quả khi DJ hiểu cách xây dựng cao trào thay vì chỉ xếp những track có drop lớn.', 'Ánh sáng, LED và bản phối cần cùng kể một hướng để crowd cảm nhận được điểm rơi của set.', 'Với các venue lớn, format này vẫn là lựa chọn an toàn để mở hoặc khóa khung prime-time.'] },
  'mc-dj-duo-format-len-ngoi': { category: 'Nightlife', date: '03 Tháng 7, 2026', title: 'MC và DJ duo format đang lên ngôi vì giữ nhịp sàn tốt hơn', summary: 'Sự phối hợp đúng lúc giữa người dẫn dắt và người điều khiển âm nhạc tạo trải nghiệm đồng bộ hơn.', image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1400&h=860&fit=crop', body: ['Duo format hiệu quả không nằm ở việc nói nhiều, mà ở việc hiểu điểm chuyển năng lượng của mỗi set.', 'MC giúp kết nối crowd và thông tin chương trình, trong khi DJ giữ chất lượng âm nhạc xuyên suốt.', 'Một brief rõ ràng trước show là yếu tố quan trọng để hai vai trò phối hợp tự nhiên.'] },
  'artist-profile-media-kit-moi': { category: 'Artist', date: '02 Tháng 7, 2026', title: 'Artist profile giờ không chỉ để đẹp mà còn là media kit để chốt booking', summary: 'Hồ sơ tốt biến thông tin nghệ sĩ thành công cụ giúp venue và agency ra quyết định nhanh hơn.', image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1400&h=860&fit=crop', body: ['Một profile chuyên nghiệp cần trả lời nhanh: nghệ sĩ là ai, phù hợp với đâu và cần điều kiện gì để biểu diễn tốt.', 'Gallery, video, audio, kinh nghiệm làm việc và booking note giúp người xem không phải rời site để tìm thêm thông tin.', 'Khi cập nhật thường xuyên, profile trở thành media kit sống có thể hỗ trợ booking và truyền thông đồng thời.'] },
  'club-opening-khong-the-thieu-visual': { category: 'Backstage', date: '01 Tháng 7, 2026', title: 'Một đêm opening thành công không thể thiếu visual concept', summary: 'Visual concept tạo ngôn ngữ nhận diện xuyên suốt từ poster đến sân khấu và nội dung recap.', image: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=1400&h=860&fit=crop', body: ['Khán giả thường cảm nhận một venue bằng hình ảnh trước cả khi bước vào không gian thật.', 'Một concept tốt cần đồng bộ giữa artwork, ánh sáng, màn hình LED và góc quay social.', 'Đầu tư vào visual giúp đội vận hành tái sử dụng tài sản nội dung cho những chiến dịch tiếp theo.'] },
  'nightlife-ha-noi-hybrid-show': { category: 'Nightlife', date: '07 Tháng 7, 2026', title: 'Nightlife Hà Nội dịch chuyển sang mô hình hybrid show', summary: 'Các venue kết hợp show trực tiếp, nội dung số và trải nghiệm hậu sự kiện để giữ nhịp kết nối với cộng đồng.', image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=1400&h=860&fit=crop', body: ['Hybrid show mở rộng giá trị của một đêm diễn vượt ra ngoài khung giờ mở cửa. Khán giả có thêm lý do để theo dõi line-up, xem recap và quay lại cho chương trình tiếp theo.', 'Với venue, dữ liệu đăng ký, nội dung video ngắn và ưu đãi sau show tạo thành một hành trình liền mạch thay vì những hoạt động tách rời.', 'Điểm quan trọng là giữ trải nghiệm trực tiếp làm trung tâm, còn các lớp nội dung số đóng vai trò kéo dài cảm xúc và kết nối cộng đồng.'] },
  'nonstop-picks-social-hook': { category: 'Xu hướng', date: '30 Tháng 6, 2026', title: 'Playlist nonstop ngắn đang trở thành social hook hiệu quả cho tab music', summary: 'Danh sách nghe nhanh giúp người dùng chạm vào âm nhạc ngay từ lần truy cập đầu tiên.', image: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1400&h=860&fit=crop', body: ['Playlist ngắn tạo một điểm bắt đầu rõ ràng cho người mới: bấm nghe ngay, cảm nhận mood và tiếp tục khám phá nghệ sĩ hoặc remix liên quan.', 'Độ dài vừa phải giúp curator duy trì chất lượng chọn lọc, đồng thời tạo cơ hội xoay vòng công bằng cho các bản nhạc mới.', 'Khi được gắn với hình ảnh và thông điệp đúng mood, nonstop trở thành một định dạng dễ chia sẻ cho cộng đồng nightlife.'] },
  'rooftop-concept-night-competition': { category: 'Sự kiện', date: '29 Tháng 6, 2026', title: 'Cuộc đua rooftop concept night đang nóng dần ở các thành phố lớn', summary: 'Concept rõ ràng đang giúp venue nổi bật hơn trong cuộc cạnh tranh về trải nghiệm đêm.', image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1400&h=860&fit=crop', body: ['Rooftop không còn chỉ là một địa điểm có tầm nhìn. Khán giả nhận diện một đêm diễn qua concept, gu âm nhạc, line-up và cách không gian được kể chuyện.', 'Các venue đầu tư vào lịch nội dung trước, trong và sau sự kiện để giữ nhịp truyền thông ổn định thay vì chỉ tập trung vào poster mở bán.', 'Một format có bản sắc giúp đội booking chọn nghệ sĩ chính xác hơn và khiến khách có lý do quay lại theo từng mùa.'] },
  'sound-design-tro-thanh-loi-the': { category: 'Artist', date: '28 Tháng 6, 2026', title: 'Producer có tư duy sound design đang sở hữu lợi thế khác biệt', summary: 'Chất liệu âm thanh riêng giúp nghệ sĩ xây nhận diện và tạo giá trị bền vững cho catalog.', image: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=1400&h=860&fit=crop', body: ['Sound design không chỉ là kỹ thuật xử lý âm thanh. Đó là cách producer tạo ra một dấu hiệu nhận diện mà người nghe có thể ghi nhớ sau vài nhịp đầu.', 'Khi màu âm thanh nhất quán, catalog trở nên rõ định vị hơn và dễ phát triển thành live set, remix hoặc các hợp tác thương hiệu.', 'Nghệ sĩ nên lưu trữ demo, phiên bản phát hành và các tài sản liên quan theo cấu trúc để dễ tái sử dụng trong những dự án sau.'] },
  'venue-membership-nightlife-loyalty': { category: 'Nightlife', date: '27 Tháng 6, 2026', title: 'Venue bắt đầu thử mô hình membership để giữ khách nightlife quay lại', summary: 'Quyền lợi theo mùa tạo thêm động lực để cộng đồng gắn bó với venue lâu dài.', image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1400&h=860&fit=crop', body: ['Membership giúp venue xây một mối quan hệ dài hạn với khách quen thay vì chỉ tập trung vào từng lượt đặt bàn riêng lẻ.', 'Ưu đãi nên gắn với trải nghiệm thực như quyền vào sớm, ưu tiên bàn, nội dung độc quyền hoặc chương trình dành cho cộng đồng.', 'Dữ liệu phản hồi từ thành viên cũng giúp venue hiểu rõ hơn những format, nghệ sĩ và khung giờ đang được yêu thích.'] },
  'dj-residency-giup-xay-cong-dong': { category: 'Artist', date: '26 Tháng 6, 2026', title: 'DJ residency đang giúp venue xây cộng đồng mạnh hơn các đêm one-off', summary: 'Một gương mặt biểu diễn ổn định giúp audience dễ nhận diện và quay lại theo chuỗi trải nghiệm.', image: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1400&h=860&fit=crop', body: ['Residency tạo nhịp hẹn định kỳ giữa nghệ sĩ, venue và khán giả. Sự lặp lại có chủ đích giúp xây dựng niềm tin và nhận diện lâu dài.', 'Để hiệu quả, mỗi buổi diễn cần có không gian cho biến hóa nhưng vẫn giữ được tinh thần chung của series.', 'Profile nghệ sĩ, lịch diễn và playlist recap là các tài sản nên được cập nhật đồng bộ để khán giả theo dõi thuận tiện.'] },
  'social-snippet-truoc-sau-show': { category: 'Backstage', date: '25 Tháng 6, 2026', title: 'Social snippet trước và sau show đang quyết định hiệu quả truyền thông', summary: 'Nội dung ngắn, đúng thời điểm giúp cảm xúc của đêm diễn tiếp tục lan tỏa trên social.', image: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=1400&h=860&fit=crop', body: ['Trước show, snippet giúp khán giả hình dung không khí và lý do để tham gia. Sau show, chúng giữ lại khoảnh khắc và tạo cầu nối cho đêm diễn tiếp theo.', 'Đội nội dung nên chuẩn bị trước danh sách cảnh quay, thông điệp và định dạng ưu tiên để không bỏ lỡ các điểm bùng nổ trong chương trình.', 'Khi kết hợp với aftermovie và playlist, những đoạn nội dung ngắn trở thành một phần của chiến lược xây cộng đồng dài hạn.'] },
}

function getArticle(slug: string): Article | undefined {
  const storedArticle = articleMap[slug] ?? feedArticleDetails[slug]
  if (storedArticle) return storedArticle
  const catalogArticle = newsCatalogSupplement.find((item) => item.slug === slug)
  return catalogArticle ? getSupplementArticleDetail(catalogArticle) : undefined
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params
  const article = getArticle(slug)
  if (!article) return {}
  return createShareMetadata({ title: article.title, description: article.summary, path: `/tin-tuc/${slug}`, image: article.image, type: 'article' })
}

export default async function ArticleDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const article = getArticle(slug)
  if (!article) notFound()
  const articles = [...Object.entries({ ...articleMap, ...feedArticleDetails }).map(([entrySlug, entry]) => ({ slug: entrySlug, ...entry })), ...newsCatalogSupplement.map(getSupplementArticleDetail)]
  const related = articles.filter((entry) => entry.slug !== slug && entry.category === article.category).concat(articles.filter((entry) => entry.slug !== slug && entry.category !== article.category)).slice(0, 3)
  const latest = articles.filter((entry) => entry.slug !== slug).slice(0, 4)
  const articleSchema = { '@context': 'https://schema.org', '@type': 'NewsArticle', headline: article.title, description: article.summary, image: [article.image], datePublished: article.date, dateModified: article.date, inLanguage: 'vi-VN', mainEntityOfPage: `${process.env.NEXT_PUBLIC_SITE_URL}/tin-tuc/${slug}`, publisher: { '@type': 'Organization', name: '9LIFE MAG' } }
  return <><main><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }} /><section className="section"><div className="container article-layout"><div className="tag-row"><span className="pill">{article.category}</span><span className="pill">{article.date}</span></div><h1 className="page-title article-title">{article.title}</h1><p className="page-intro article-summary">{article.summary}</p><ArticleShareButton slug={slug} title={article.title} /><img className="article-hero-image" src={article.image} alt="" />
    <div className="article-body-shell">{article.body.map((paragraph) => <p key={paragraph} className="article-paragraph">{paragraph}</p>)}</div>
    <section className="article-continue-section"><div className="article-section-head"><div><p className="section-eyebrow">Continue Reading</p><h2>Đọc tiếp cùng chủ đề</h2></div><Link href="/tin-tuc" className="view-more-link">Xem tất cả tin</Link></div><div className="article-related-grid">{related.map((entry) => <Link key={entry.slug} href={`/tin-tuc/${entry.slug}`} className="article-related-card"><img src={entry.image} alt="" /><div><span>{entry.category} • {entry.date}</span><strong>{entry.title}</strong><p>{entry.summary}</p></div></Link>)}</div></section>
    <section className="article-latest-section"><div><p className="section-eyebrow">Latest Feed</p><h2>Không bỏ lỡ những bài mới</h2></div><div className="article-latest-list">{latest.map((entry) => <Link key={entry.slug} href={`/tin-tuc/${entry.slug}`}><span>{entry.category}</span><strong>{entry.title}</strong><small>{entry.date}</small></Link>)}</div></section>
    <div className="article-actions"><Link href="/tin-tuc" className="button-secondary">Khám phá thêm tin tức</Link><Link href="/" className="button-secondary">Về trang chủ</Link></div></div></section></main><ContentDiscovery current={{ kind: 'article', id: slug }} /></>
}
